# Generated by Django 5.2.9 on 2026-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registereduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='password',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='keycloak_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
