# Generated by Django 5.2.9 on 2026-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_registereduser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
